name: unofficial_jisho_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.example.com #TODO: EDIT

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  xml: ^3.7.0
  html_unescape: ^1.0.1+3
  html: ^0.14.0+3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
