name: unofficial_jisho_api
version: 3.0.0

description: An unofficial api for searching and scraping the japanese dictionary Jisho.org
homepage: https://github.com/h7x4ABk3g/unofficial_jisho_api_dart/
issue_tracker: https://github.com/h7x4ABk3g/unofficial_jisho_api_dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  html_unescape: ^2.0.0
  html: ^0.15.0
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
  path: ^1.8.0
  effective_dart: ^1.3.2
