name: unofficial_jisho_api
description: An unofficial api for searching and scraping the japanese dictionary Jisho.org
version: 1.0.0
repository: https://github.com/h7x4ABk3g/unofficial_jisho_api_dart/
issue_tracker: https://github.com/h7x4ABk3g/unofficial_jisho_api_dart/issues


environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.1
  html_unescape: ^1.0.1+3
  html: ^0.14.0+3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
  path: ^1.7.0
  effective_dart: ^1.2.3
